Repository ko9612/Hobbyt, pull requests merged in 2022-12, with the labels that each got.

#6 개발 환경 세팅
  .github/ISSUE_TEMPLATE/❗-be--issue-template.md
  .github/ISSUE_TEMPLATE/❗-fe--issue-template.md
  .github/ISSUE_TEMPLATE/🌟-be--feature-template.md
  .github/ISSUE_TEMPLATE/🌟-fe--feature-template.md
  .github/ISSUE_TEMPLATE/🤬bugfix-template.md
  .gitignore
  README.md
  client/.eslintrc.js
  client/.gitignore
  client/.prettierrc.json
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/index.tsx
  client/postcss.config.js
  client/public/favicon.ico
  client/public/next.svg
  client/public/thirteen.svg
  client/public/vercel.svg
  client/src/components/Button/example.tsx
  client/src/components/Footer/example.tsx
  client/src/components/Modal/example.tsx
  client/src/components/Nav/example.tsx
  client/src/components/ToastUI/example.tsx
  client/src/components/UserHome/example.tsx
  client/src/image/example.tsx
  client/styles/globals.css
  client/tailwind.config.js
  client/tsconfig.json
  server/example.tsx
Labels: ⚙Setting

#8 style: 전체, 개인홈, 블로그 목업 #7
  client/pages/_app.tsx
  client/pages/blog.tsx
  client/pages/index.tsx
  client/src/components/Tab/BlogTab.tsx
  client/src/components/UserHome/DMButton.tsx
  client/src/components/UserHome/FollowButton.tsx
  client/src/components/UserHome/Following.tsx
  client/src/components/UserHome/Header.tsx
  client/src/components/UserHome/UserProfile.tsx
  client/src/components/UserHome/UserProfileImage.tsx
  client/src/components/UserHome/example.tsx
  client/src/image/header_ex.jpg
  client/src/image/userProfile_ex.jpeg
  client/styles/globals.css
  client/tsconfig.json
Labels: 🎨CSS, Frontend

#10 style: 개인홈 목업#7
  client/pages/blog.tsx
  client/src/components/Tab/BlogList.tsx
  client/src/components/Tab/BlogTab.tsx
  client/src/components/ViewLikeWrite/LikeCount.tsx
  client/src/components/ViewLikeWrite/TodayCount.tsx
  client/src/components/ViewLikeWrite/ViewCount.tsx
  client/src/components/ViewLikeWrite/WriteDate.tsx
  client/styles/globals.css
  client/tailwind.config.js
Labels: 🎨CSS, Frontend

#12 Feat/seongho/abstraction #11
  server/src/main/java/com/hobbyt/global/entity/Article.java
  server/src/main/java/com/hobbyt/global/entity/BaseEntity.java
Labels: Backend, 🌟Feature

#14 chore: applicaiton.yml 작성
  server/src/main/resources/application-dev.yml
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: ⚙Setting, Backend

#15 style: 개인홈 판매 목업 #7
  client/pages/blog.tsx
  client/src/components/Button/DMButton.tsx
  client/src/components/Button/DefalutButton.tsx
  client/src/components/Button/FilterButton.tsx
  client/src/components/Button/FollowButton.tsx
  client/src/components/Button/example.tsx
  client/src/components/Tab/BlogList.tsx
  client/src/components/Tab/BlogTab.tsx
  client/src/components/Tab/SaleList.tsx
  client/src/components/UserHome/BlogSaleInfo.tsx
  client/src/components/UserHome/Following.tsx
  client/src/components/UserHome/Header.tsx
  client/src/components/UserHome/UserProfile.tsx
  client/src/components/ViewLikeWrite/TodayCount.tsx
Labels: 🎨CSS, Frontend
