Repository ko9612/Hobbyt, pull requests merged in 2023-01, with the labels that each got.

#19 style: 블로그 작성 페이지 목업 #7
  client/pages/blogwrite.tsx
  client/src/components/Tag/DefalutTag.tsx
  client/src/components/ToastUI/TitleInput.tsx
  client/src/components/Togle/DefalutTogle.tsx
  client/styles/globals.css
Labels: 🎨CSS, Frontend

#20 feat: 회원, 주문 관련 엔티티 추가
  server/src/main/java/com/hobbyt/domain/entity/Authority.java
  server/src/main/java/com/hobbyt/domain/entity/Order.java
  server/src/main/java/com/hobbyt/domain/entity/OrderItem.java
  server/src/main/java/com/hobbyt/domain/entity/OrderStatus.java
  server/src/main/java/com/hobbyt/domain/entity/Product.java
  server/src/main/java/com/hobbyt/domain/entity/Sale.java
  server/src/main/java/com/hobbyt/domain/entity/User.java
  server/src/main/java/com/hobbyt/domain/entity/UserStatus.java
Labels: ⚙Setting, Backend

#22 fix: 생성일자, 수정일자 적용 해결
  server/src/main/java/com/hobbyt/HobbytApplication.java
Labels: 🤬BugFix, Backend

#24 feat:Nav,Footer 작성
  client/package-lock.json
  client/pages/_app.tsx
  client/pages/blog.tsx
  client/pages/index.tsx
  client/pages/signin.tsx
  client/pages/signup.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Nav/NavArr.tsx
  client/src/components/Nav/NavBar.tsx
  client/src/components/Nav/PcNav.tsx
  client/src/components/Nav/SearchBar.tsx
  client/src/components/Nav/example.tsx
  client/src/image/logo.png
  client/src/image/logoText.png
  client/src/image/mainLogo.png
Labels: 🎨CSS, Frontend, 🌟Feature

#27 Feat/seongho/post #25
  server/src/main/java/com/hobbyt/global/entity/Tag.java
  server/src/main/java/com/hobbyt/post/entity/Post.java
  server/src/main/java/com/hobbyt/post/entity/PostComment.java
  server/src/main/java/com/hobbyt/post/entity/PostLike.java
  server/src/main/java/com/hobbyt/post/entity/PostTag.java
Labels: Backend, 🌟Feature

#28 Feat/seongho/chat noti #26
  server/src/main/java/com/hobbyt/chat/entity/ChatMessage.java
  server/src/main/java/com/hobbyt/chat/entity/ChatRoom.java
  server/src/main/java/com/hobbyt/chat/entity/ChatUser.java
  server/src/main/java/com/hobbyt/notification/entity/Notification.java
  server/src/main/java/com/hobbyt/notification/entity/NotificationType.java
Labels: Backend, 🌟Feature

#29 Feat/hana/modal mockup #05
  client/pages/index.tsx
  client/pages/signin.tsx
  client/src/components/Modal/DelModal.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Modal/example.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Nav/NavBar.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Nav/PcNav.tsx
Labels: 🎨CSS, Frontend, 🌟Feature

#30 Feat/hana/modal mockup #05
  client/.eslintrc.js
  client/pages/index.tsx
  client/src/components/Modal/DelModal.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Modal/UnFollowModal.tsx
Labels: 🎨CSS, Frontend, 🌟Feature

#33 layout: SignIn 작성
  client/pages/signin.tsx
  client/src/components/Button/SignupButton.tsx
  client/src/components/Button/SocialButton.tsx
  client/src/components/Button/WideButton.tsx
  client/src/components/Input/LoginInput.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/image/example.tsx
  client/src/image/logo.png
  client/src/image/logoText.png
  client/src/image/mainLogo.png
Labels: 🎨CSS, Frontend, 🌟Feature

#35 style: 내 정보 목업 #7
  client/pages/mypage.tsx
  client/src/components/List/ProductsList.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tab/TabArr.tsx
Labels: 🎨CSS, Frontend

#37 Layout: Main mockup
  client/pages/blogwrite.tsx
  client/pages/index.tsx
  client/pages/signin.tsx
  client/pages/signup.tsx
  client/pages/test.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Nav/PcNav.tsx
  client/src/components/Sign/SignGuide.tsx
  client/src/components/Sign/SignLogo.tsx
  client/src/components/Sign/SignRightContent.tsx
  client/src/components/Sign/SigninForm.tsx
  client/src/components/Sign/SignupForm.tsx
  client/src/components/Sign/SocialForm.tsx
  client/src/components/UserHome/ProfileEdit.tsx
Labels: 🏭Refactor, 🎨CSS, Frontend

#38 feat: 메일 인증 회원가입 구현
  server/build.gradle
  server/src/main/java/com/hobbyt/domain/entity/Account.java
  server/src/main/java/com/hobbyt/domain/entity/Address.java
  server/src/main/java/com/hobbyt/domain/entity/Order.java
  server/src/main/java/com/hobbyt/domain/entity/Period.java
  server/src/main/java/com/hobbyt/domain/entity/Sale.java
  server/src/main/java/com/hobbyt/domain/user/controller/AuthController.java
  server/src/main/java/com/hobbyt/domain/user/controller/UserController.java
  server/src/main/java/com/hobbyt/domain/user/dto/request/EmailRequest.java
  server/src/main/java/com/hobbyt/domain/user/dto/request/SignupRequest.java
  server/src/main/java/com/hobbyt/domain/user/entity/Authority.java
  server/src/main/java/com/hobbyt/domain/user/entity/User.java
  server/src/main/java/com/hobbyt/domain/user/entity/UserStatus.java
  server/src/main/java/com/hobbyt/domain/user/repository/UserRepository.java
  server/src/main/java/com/hobbyt/domain/user/service/AuthService.java
  server/src/main/java/com/hobbyt/domain/user/service/AuthenticationCode.java
  server/src/main/java/com/hobbyt/domain/user/service/MailContentBuilder.java
  server/src/main/java/com/hobbyt/domain/user/service/MailService.java
  server/src/main/java/com/hobbyt/domain/user/service/NotificationEmail.java
  server/src/main/java/com/hobbyt/domain/user/service/UserService.java
  server/src/main/java/com/hobbyt/global/config/AsyncConfig.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/error/exception/CMailException.java
  server/src/main/java/com/hobbyt/global/error/exception/UserExistException.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/authCodeMail.html
  server/src/test/java/com/hobbyt/domain/user/controller/AuthControllerTest.java
  server/src/test/java/com/hobbyt/domain/user/controller/UserControllerTest.java
  server/src/test/java/com/hobbyt/domain/user/service/AuthServiceTest.java
  server/src/test/java/com/hobbyt/domain/user/service/AuthenticationCodeTest.java
  server/src/test/java/com/hobbyt/domain/user/service/MailContentBuilderTest.java
  server/src/test/java/com/hobbyt/domain/user/service/MailServiceTest.java
  server/src/test/java/com/hobbyt/domain/user/service/UserServiceTest.java
Labels: ✅Test, Backend, 🌟Feature

#42 Layout: 내 정보 관리 목업
  client/pages/index.tsx
  client/pages/mypage.tsx
  client/src/components/Button/DefalutButton.tsx
  client/src/components/Button/InfoEditButton.tsx
  client/src/components/Button/ModalButton.tsx
  client/src/components/Button/SubmitButton.tsx
  client/src/components/Input/DefaultInput.tsx
  client/src/components/Input/LoginInput.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/MyList/MyInfoList.tsx
  client/src/components/List/MyList/ProductsList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Modal/UnFollowModal.tsx
  client/src/components/Nav/NavArr.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Nav/SearchBar.tsx
  client/src/components/Sign/SigninForm.tsx
  client/src/components/Sign/SignupForm.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/UserHome/BlogSaleInfo.tsx
  client/src/components/UserHome/DefaultProfileImg.tsx
  client/src/components/UserInfo/AccountInfo.tsx
  client/src/components/UserInfo/AddressInfo.tsx
  client/src/components/UserInfo/InfoStyle.tsx
  client/src/components/UserInfo/PasswordInfo.tsx
  client/src/components/UserInfo/RefundInfo.tsx
Labels: 🏭Refactor, 🎨CSS, Frontend

#43 style: 전체 레이아웃 통일 #7
  client/pages/_app.tsx
  client/pages/blog.tsx
  client/pages/index.tsx
  client/pages/mypage.tsx
  client/src/components/Category/CategoryArr.tsx
  client/src/components/Category/MyPageCategory.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/MyCommentList.tsx
  client/src/components/List/MyList/ProductsList.tsx
  client/src/components/List/MyList/PurchaseList.tsx
  client/src/components/List/MyList/SalesManagementList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Nav/PcNav.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/UserHome/Header.tsx
Labels: 🎨CSS, Frontend

#44 style: 개인홈 레이아웃 정리 #7
  client/pages/blog.tsx
  client/pages/mypage.tsx
  client/src/components/Category/CategoryArr.tsx
  client/src/components/Category/MyPageCategory.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/MyCommentList.tsx
  client/src/components/List/MyList/ProductsList.tsx
  client/src/components/List/MyList/PurchaseList.tsx
  client/src/components/List/MyList/SalesManagementList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Tab/Tab.tsx
  client/styles/globals.css
Labels: 🎨CSS, Frontend

#45 style: 알림페이지 레이아웃 #7
  client/pages/blog.tsx
  client/pages/index.tsx
  client/pages/mypage.tsx
  client/pages/notice.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/List/NoticeList.tsx
Labels: 🎨CSS, Frontend

#46 style: 메세지 페이지 목업 #7
  client/pages/message.tsx
  client/pages/notice.tsx
  client/src/components/List/NoticeList.tsx
  client/src/components/Message/DefaultMessage.tsx
  client/src/components/Message/MessageList.tsx
Labels: 🎨CSS, Frontend

#47 Layout: 판매 게시글 작성 목업+수정
  client/pages/salewrite.tsx
Labels: 🏭Refactor, 🎨CSS, Frontend, 🌟Feature

#48 style: 전체 레이아웃 통일 #7
  client/pages/blogwrite.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Message/ChatRoom.tsx
  client/src/components/Message/MessageList.tsx
  client/src/components/Nav/NavArr.tsx
  client/src/components/Tag/DefalutTag.tsx
  client/src/components/UserHome/BlogSaleInfo.tsx
  client/src/components/UserHome/ProfileEdit.tsx
  client/src/components/UserHome/UserProfile.tsx
Labels: 🎨CSS, Frontend

#53 style: 검색 결과 페이지 목업 #40
  client/pages/index.tsx
  client/pages/search.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Nav/PcNav.tsx
  client/src/components/Nav/SearchBar.tsx
  client/src/components/SaleWrite/ProductInfoInput.tsx
  client/src/components/SaleWrite/ShippingInfoInput.tsx
  client/src/components/Search/SearchBar.tsx
  client/src/components/Search/SearchBlog.tsx
  client/src/components/Search/SearchSales.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tab/TabArr.tsx
Labels: 🏭Refactor, 🎨CSS, Frontend, 🌟Feature

#54 style: 주문상세 페이지 목업 #40
  client/pages/orderdetail.tsx
  client/pages/search.tsx
  client/src/components/Button/DefalutButton.tsx
  client/src/components/List/MyList/PurchaseList.tsx
  client/src/components/OrderListInfo/DepositInfo.tsx
  client/src/components/OrderListInfo/OrderInfo.tsx
  client/src/components/OrderListInfo/OrderProgress.tsx
  client/src/components/OrderListInfo/PurChaserInfo.tsx
  client/src/components/OrderListInfo/SellerInfo.tsx
  client/src/components/Search/SearchBlog.tsx
Labels: 🏭Refactor, 🎨CSS, Frontend

#57 feat: 블로그 디테일#56
  client/dummy/blogdummy.tsx
  client/pages/blogdetail.tsx
  client/src/api/blogApi.tsx
  client/src/components/List/Comment/CommentInput.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/PostDetail/BlogPostDetail.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/ViewLikeWrite/LikeCount.tsx
  client/src/components/ViewLikeWrite/ViewCount.tsx
  client/src/components/ViewLikeWrite/WriteDate.tsx
Labels: 🎨CSS, Frontend

#60 setting: 컴포넌트 폴더 정리
  client/pages/blog.tsx
  client/pages/blogdetail.tsx
  client/pages/blogwrite.tsx
  client/pages/orderdetail.tsx
  client/pages/profile.tsx
  client/pages/salewrite.tsx
  client/pages/search.tsx
  client/pages/signin.tsx
  client/pages/signup.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/MyList/MyInfoList.tsx
  client/src/components/List/NoticeList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Message/MessageList.tsx
  client/src/components/Modal/UnFollowModal.tsx
  client/src/components/Nav/NavArr.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/OrderListInfo/DepositInfo.tsx
  client/src/components/Page/OrderListInfo/OrderInfo.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/OrderListInfo/PurChaserInfo.tsx
  client/src/components/Page/OrderListInfo/SellerInfo.tsx
  client/src/components/Page/PostDetail/BlogPostDetail.tsx
  client/src/components/Page/SaleWrite/AccountInput.tsx
  client/src/components/Page/SaleWrite/PostWriteStyle.tsx
  client/src/components/Page/SaleWrite/ProcessUrlInput.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/SaleWrite/RefundGuideInput.tsx
  client/src/components/Page/SaleWrite/SalePeriodInput.tsx
  client/src/components/Page/SaleWrite/SendTimeInput.tsx
  client/src/components/Page/SaleWrite/ShippingInfoInput.tsx
  client/src/components/Page/SaleWrite/WarningInput.tsx
  client/src/components/Page/Search/SearchBar.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Search/SearchSales.tsx
  client/src/components/Page/Sign/SignGuide.tsx
  client/src/components/Page/Sign/SignLogo.tsx
  client/src/components/Page/Sign/SignRightContent.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/Sign/SignupForm.tsx
  client/src/components/Page/Sign/SocialForm.tsx
  client/src/components/Page/UserHome/BlogSaleInfo.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/Page/UserHome/Following.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/Page/UserHome/UserProfileImage.tsx
  client/src/components/Page/UserInfo/AccountInfo.tsx
  client/src/components/Page/UserInfo/AddressInfo.tsx
  client/src/components/Page/UserInfo/InfoStyle.tsx
  client/src/components/Page/UserInfo/PasswordInfo.tsx
  client/src/components/Page/UserInfo/RefundInfo.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/ViewLikeWrite/LikeCount.tsx
Labels: Frontend

#61 style: 판매 상세+결제 모달 #40
  client/pages/saledetail.tsx
  client/pages/salewrite.tsx
  client/src/components/Button/SubmitButton.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Modal/PaymentModal.tsx
  client/src/components/Page/MyList/MyInfoList.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/MyList/PurchaseList.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/src/components/Page/OrderListInfo/DepositInfo.tsx
  client/src/components/Page/OrderListInfo/OrderInfo.tsx
  client/src/components/Page/SaleDetail/Agreement.tsx
  client/src/components/Page/SaleDetail/InputForPurchase.tsx
  client/src/components/Page/SaleDetail/ProductContent.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Page/SaleDetail/ProductList.tsx
  client/src/components/Page/SaleDetail/ProductTitle.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Sign/SignupForm.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/UserProfileImage.tsx
  client/src/components/Page/UserInfo/InfoStyle.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/ViewLikeWrite/LikeCount.tsx
  client/src/components/ViewLikeWrite/ViewCount.tsx
  client/src/components/ViewLikeWrite/WriteDate.tsx
Labels: 🏭Refactor, 🎨CSS, Frontend, 🌟Feature

#65 feat: 블로그 기능 구현 #56
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/blogdetail.tsx
  client/pages/blogwrite.tsx
  client/src/api/blogApi.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Tag/DefalutTag.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/ToastUI/TitleInput.tsx
  client/src/setupProxy.js
  client/src/state/Blog/ContentState.tsx
  client/src/state/Blog/TitleState.tsx
  client/src/state/Sale/SaleState.tsx
  client/tsconfig.json
Labels: Frontend, 🌟Feature

#66 feat: proxy설정 수정
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/api/blogApi.tsx
  client/src/api/errorHandler.tsx
  client/src/api/testApi.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/setupProxy.js
Labels: Frontend, 🌟Feature

#67 feat: 블로그 C 완료 #56
  client/package-lock.json
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Tag/DefalutTag.tsx
  client/src/state/Blog/TagState.tsx
Labels: Frontend, 🌟Feature

#73 feat: signup 기능 구현(중복 처리x) #72
  client/next.config.js
  client/pages/salewrite.tsx
  client/src/api/signupApi.tsx
  client/src/components/Button/DefalutButton.tsx
  client/src/components/Button/SubmitButton.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/Sign/SignupForm.tsx
  client/src/state/signupState.tsx
  client/src/util/Regex.tsx
Labels: Frontend, 🌟Feature

#74 refactor: useForm 사용해서 signup 재구현 #72
  client/package-lock.json
  client/package.json
  client/pages/signup.tsx
  client/src/api/signApi.tsx
  client/src/components/Button/DefalutButton.tsx
  client/src/components/Button/SubmitButton.tsx
  client/src/components/Page/Sign/SignupForm.tsx
  client/src/state/signupState.tsx
Labels: 🏭Refactor, Frontend, 🌟Feature

#76 feat: 로그인 구현 중
  client/pages/signup.tsx
  client/src/api/signApi.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/Sign/SignupForm.tsx
  client/src/state/UserState.tsx
Labels: Frontend, 🌟Feature

#77 feat:프로필 수정 기능구현 #75
  client/src/api/blogApi.tsx
  client/src/components/Button/DefalutButton.tsx
  client/src/components/Button/InfoEditButton.tsx
  client/src/components/Button/ModalButton.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/UserHome/BlogSaleInfo.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Page/UserInfo/AddressInfo.tsx
  client/src/components/Page/UserInfo/PasswordInfo.tsx
Labels: Frontend, 🌟Feature

#81 refactor: 회원관련 api 정리
  server/src/main/java/com/hobbyt/domain/entity/Recipient.java
  server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java
  server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java
  server/src/main/java/com/hobbyt/domain/member/dto/TokenDto.java
  server/src/main/java/com/hobbyt/domain/member/entity/Member.java
  server/src/main/java/com/hobbyt/domain/member/repository/MemberRepository.java
  server/src/main/java/com/hobbyt/domain/member/service/AuthService.java
  server/src/main/java/com/hobbyt/domain/member/service/AuthenticationCode.java
  server/src/main/java/com/hobbyt/domain/member/service/MailContentBuilder.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/error/advice/ExceptionAdvice.java
  server/src/main/java/com/hobbyt/global/error/exception/LoginFailException.java
  server/src/main/java/com/hobbyt/global/error/filter/ExceptionHandlerFilter.java
  server/src/main/java/com/hobbyt/global/security/dto/LoginRequest.java
  server/src/main/java/com/hobbyt/global/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/hobbyt/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/hobbyt/global/security/jwt/JwtTokenProvider.java
  server/src/main/java/com/hobbyt/global/security/member/MemberDetails.java
  server/src/main/java/com/hobbyt/global/security/service/MemberDetailsService.java
  server/src/test/java/com/hobbyt/config/TestMemberDetailService.java
  server/src/test/java/com/hobbyt/domain/member/controller/AuthControllerTest.java
  server/src/test/java/com/hobbyt/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/hobbyt/domain/member/service/AuthServiceTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MailContentBuilderTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MemberServiceTest.java
  server/src/test/java/com/hobbyt/util/TestUtil.java
Labels: 🏭Refactor

#84 feat: MemberService에서 email로 찾아오는 것으로 변경 (#82)
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostCommentController.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostController.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostLikeController.java
  server/src/main/java/com/hobbyt/domain/post/service/PostCommentService.java
  server/src/main/java/com/hobbyt/domain/post/service/PostLikeService.java
  server/src/main/java/com/hobbyt/domain/post/service/PostService.java
Labels: Backend, 🚀API

#85 feat: 로그인, 로그아웃 #72
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/api/signApi.tsx
  client/src/components/Modal/DelModal.tsx
  client/src/components/Modal/DeleteModal.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Nav/NavArr.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/Sign/SignupForm.tsx
  client/src/components/Page/Sign/Token.tsx
  client/src/state/UserState.tsx
  client/src/type/userTypes.tsx
  client/src/util/loginRefresh.tsx
Labels: Frontend, 🌟Feature

#86 fix: secret key 길이에 따른 알고리즘 적용 문제 해결
  server/src/main/java/com/hobbyt/global/security/jwt/JwtTokenProvider.java
Labels: 🤬BugFix

#87 Feat/seongho/blog #78
  server/src/main/java/com/hobbyt/domain/post/controller/PostCommentController.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostController.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostLikeController.java
  server/src/main/java/com/hobbyt/domain/post/dto/PostResponse.java
  server/src/main/java/com/hobbyt/domain/post/repository/CustomPostRepository.java
  server/src/main/java/com/hobbyt/domain/post/repository/CustomPostRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/post/repository/PostRepository.java
  server/src/main/java/com/hobbyt/domain/post/service/PostService.java
Labels: Backend, 🚀API

#89 feat: 블로그 상세 #88
  client/pages/blog.tsx
  client/pages/post/[id].tsx
  client/src/api/tabApi.tsx
  client/src/components/Button/InfoEditButton.tsx
  client/src/components/Button/ProfileButton.tsx
  client/src/components/Category/MyPageCategory.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Message/MessageList.tsx
  client/src/components/Modal/UnFollowModal.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Nav/NavArr.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tag/DefalutTag.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/ToastUI/TitleInput.tsx
  client/src/components/Togle/DefalutTogle.tsx
  client/src/components/ViewLikeWrite/LikeCount.tsx
  client/src/components/ViewLikeWrite/ViewCount.tsx
  client/src/components/ViewLikeWrite/WriteDate.tsx
  client/src/state/Blog/ContentState.tsx
  client/src/state/Blog/TagState.tsx
  client/src/state/Blog/TitleState.tsx
  client/src/state/BlogPostState.tsx
  client/src/state/QueryState.tsx
  client/src/state/SaleState.tsx
  client/src/state/UserState.tsx
  client/src/type/blogType.tsx
Labels: Frontend, 🌟Feature

#91 fix: 블로그 게시물 상세 조회 수정 (#90)
  server/src/main/java/com/hobbyt/domain/post/controller/PostController.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostLikeController.java
  server/src/main/java/com/hobbyt/domain/post/dto/PostRequest.java
  server/src/main/java/com/hobbyt/domain/post/dto/PostResponse.java
  server/src/main/java/com/hobbyt/domain/post/entity/Post.java
  server/src/main/java/com/hobbyt/domain/post/repository/CustomPostRepository.java
  server/src/main/java/com/hobbyt/domain/post/repository/CustomPostRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/post/service/PostService.java
  server/src/main/java/com/hobbyt/domain/tag/entity/Tag.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/entity/Article.java
Labels: 🤬BugFix, Backend, 🚀API

#93 Feat/seongho/blog list #92
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/member/repository/MemberRepository.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostCommentController.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostController.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostLikeController.java
  server/src/main/java/com/hobbyt/domain/post/entity/PostLike.java
  server/src/main/java/com/hobbyt/domain/post/entity/PostTag.java
  server/src/main/java/com/hobbyt/domain/post/repository/CustomPostRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/post/service/PostService.java
  server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeBlogResponse.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeRequest.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeServiceDto.java
  server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java
Labels: Backend, 🚀API

#94 feat: 블로그 상세 api 연결 #88
  client/next.config.js
  client/pages/blog.tsx
  client/pages/blogdetail.tsx
  client/pages/post/[id].tsx
  client/src/api/blogApi.tsx
  client/src/api/profileApi.tsx
  client/src/api/signApi.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Scroll/InfiniteScroll.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tag/DefalutTag.tsx
  client/src/components/ToastUI/TextViewer.tsx
  client/src/state/BlogPostState.tsx
Labels: Frontend, 🌟Feature

#95 feat: token 발급 로직 작성(임시), 회원탈퇴 구현
  client/pages/message.tsx
  client/pages/notice.tsx
  client/src/api/signApi.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Nav/NavArr.tsx
  client/src/components/Nav/NavBar.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Nav/PcNav.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/Sign/Token.tsx
  client/src/components/Page/UserInfo/AccountInfo.tsx
  client/src/util/LoginRefresh.tsx
  client/src/util/loginRefresh.tsx
  client/state/Blog/ContentState.tsx
  client/state/Blog/TagState.tsx
  client/state/Blog/TitleState.tsx
  client/state/Sale/SaleState.tsx
  client/state/UserState.tsx
Labels: Frontend, 🌟Feature

#97 faet: 프로필 수정 기능구현 완료#75
  client/package-lock.json
  client/pages/blogwrite.tsx
  client/pages/message.tsx
  client/pages/mypage.tsx
  client/pages/notice.tsx
  client/src/api/profileApi.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/Page/UserHome/UserProfileImage.tsx
  client/src/components/ToastUI/TextViewer.tsx
  client/src/state/ProfileState.tsx
Labels: Frontend, 🌟Feature

#98 Feat/hana/my page #96
  client/pages/mypage.tsx
  client/pages/orderdetail.tsx
  client/pages/orderdetail/[id].tsx
  client/src/api/signApi.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Nav/NavBar.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/UserInfo/AccountInfo.tsx
  client/src/state/UserState.tsx
  client/src/util/LoginRefresh.tsx
  client/state/Blog/ContentState.tsx
  client/state/Blog/TagState.tsx
  client/state/Blog/TitleState.tsx
  client/state/Sale/SaleState.tsx
  client/state/UserState.tsx
Labels: 🤬BugFix, Frontend

#100 feat: 개인홈 댓글 리스트 구현 (#99)
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeCommentResponse.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeServiceDto.java
  server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java
Labels: Backend, 🚀API

#101 Feat/seongho/blog search #64
  server/src/main/java/com/hobbyt/domain/search/controller/SearchController.java
  server/src/main/java/com/hobbyt/domain/search/dto/OrderBy.java
  server/src/main/java/com/hobbyt/domain/search/dto/SearchPostResponse.java
  server/src/main/java/com/hobbyt/domain/search/dto/SearchRequest.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepository.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/search/service/SearchService.java
  server/src/main/java/com/hobbyt/domain/search/service/SearchServiceImpl.java
  server/src/main/java/com/hobbyt/global/healthcheck/HealthCheckController.java
Labels: Backend, 🚀API

#102 Feat/seongho/blog search #64
  server/src/main/java/com/hobbyt/HobbytApplication.java
  server/src/main/java/com/hobbyt/domain/main/controller/MainController.java
  server/src/main/java/com/hobbyt/domain/main/dto/HotPost.java
  server/src/main/java/com/hobbyt/domain/main/dto/HotPostResponse.java
  server/src/main/java/com/hobbyt/domain/main/repository/HotPostRepository.java
  server/src/main/java/com/hobbyt/domain/main/repository/MainRepository.java
  server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/main/service/MainService.java
Labels: Backend, 🚀API

#103 feat: 판매 게시글 등록 구현, 요구사항에 따른 api 변경
  server/src/main/java/com/hobbyt/domain/entity/OrderItem.java
  server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java
  server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java
  server/src/main/java/com/hobbyt/domain/member/dto/LoginResponse.java
  server/src/main/java/com/hobbyt/domain/member/dto/request/UpdateMyInfoRequest.java
  server/src/main/java/com/hobbyt/domain/member/dto/response/MyInfoResponse.java
  server/src/main/java/com/hobbyt/domain/member/dto/response/ProfileResponse.java
  server/src/main/java/com/hobbyt/domain/member/entity/Member.java
  server/src/main/java/com/hobbyt/domain/member/entity/Recipient.java
  server/src/main/java/com/hobbyt/domain/member/entity/Views.java
  server/src/main/java/com/hobbyt/domain/member/service/AuthService.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/ProductRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Delivery.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Product.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java
  server/src/main/java/com/hobbyt/domain/sale/entity/SaleLike.java
  server/src/main/java/com/hobbyt/domain/sale/entity/SaleTag.java
  server/src/main/java/com/hobbyt/domain/sale/repository/ProductRepository.java
  server/src/main/java/com/hobbyt/domain/sale/repository/SaleRepository.java
  server/src/main/java/com/hobbyt/domain/sale/repository/SaleTagRepository.java
  server/src/main/java/com/hobbyt/domain/sale/service/ProductService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleTagService.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/entity/Account.java
  server/src/main/java/com/hobbyt/global/entity/Address.java
  server/src/main/resources/application.yml
  server/src/test/java/com/hobbyt/domain/member/controller/AuthControllerTest.java
  server/src/test/java/com/hobbyt/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/hobbyt/domain/member/service/AuthServiceTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MemberServiceTest.java
  server/src/test/java/com/hobbyt/util/TestUtil.java
Labels: 🏭Refactor, Backend, 🌟Feature

#104 feat:댓글 수정,삭제 #79
  client/pages/post/[id].tsx
  client/src/api/blogApi.tsx
  client/src/api/profileApi.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Comment/CommentInput.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/Modal/EditModal.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
  client/src/components/Tab/Tab.tsx
  client/src/state/UserState.tsx
  client/src/type/blogType.tsx
Labels: Frontend, 🌟Feature

#106 feat: 내 정보 수정 기능 완료 #96
  client/package-lock.json
  client/package.json
  client/src/api/errorHandler.tsx
  client/src/api/signApi.tsx
  client/src/api/userApi.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Nav/NavBar.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/MyList/MyInfoList.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/Sign/SignupForm.tsx
  client/src/components/Page/UserInfo/AccountInfo.tsx
  client/src/components/Page/UserInfo/AddressInfo.tsx
  client/src/components/Page/UserInfo/InfoStyle.tsx
  client/src/components/Page/UserInfo/PasswordInfo.tsx
  client/src/components/Page/UserInfo/RefundInfo.tsx
  client/src/state/UserState.tsx
  client/src/type/userTypes.tsx
  client/src/util/LoginRefresh.tsx
  client/src/util/Regex.tsx
Labels: Frontend, 🌟Feature

#108 Feat/seongho/comment alram #107
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/notification/controller/NotificationController.java
  server/src/main/java/com/hobbyt/domain/notification/dto/NotificationEvent.java
  server/src/main/java/com/hobbyt/domain/notification/dto/NotificationRequest.java
  server/src/main/java/com/hobbyt/domain/notification/dto/NotificationResponse.java
  server/src/main/java/com/hobbyt/domain/notification/entity/Notification.java
  server/src/main/java/com/hobbyt/domain/notification/entity/NotificationType.java
  server/src/main/java/com/hobbyt/domain/notification/repository/CustomNotificationRepository.java
  server/src/main/java/com/hobbyt/domain/notification/repository/CustomNotificationRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/notification/repository/EmitterRepository.java
  server/src/main/java/com/hobbyt/domain/notification/repository/EmitterRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/notification/repository/NotificationRepository.java
  server/src/main/java/com/hobbyt/domain/notification/service/NotificationEventHandler.java
  server/src/main/java/com/hobbyt/domain/notification/service/NotificationService.java
  server/src/main/java/com/hobbyt/domain/notification/service/SseService.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostController.java
  server/src/main/java/com/hobbyt/domain/post/entity/PostComment.java
  server/src/main/java/com/hobbyt/domain/post/repository/CustomPostRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/post/repository/CustomPostTagRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/post/service/PostCommentService.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeRequest.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeServiceDto.java
  server/src/main/java/com/hobbyt/domain/search/dto/SearchRequest.java
  server/src/main/java/com/hobbyt/global/config/QueryDslConfig.java
  server/src/main/java/com/hobbyt/global/error/exception/SseConnectException.java
  server/src/main/resources/application.yml
Labels: Backend, 🚀API

#109 feat: 판매 게시글 변경, 삭제 구현
  server/src/main/java/com/hobbyt/domain/entity/OrderItem.java
  server/src/main/java/com/hobbyt/domain/order/entity/Order.java
  server/src/main/java/com/hobbyt/domain/order/entity/OrderItem.java
  server/src/main/java/com/hobbyt/domain/order/entity/OrderStatus.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Product.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomProductRepository.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomProductRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomSaleTagRepository.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomSaleTagRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/sale/repository/ProductRepository.java
  server/src/main/java/com/hobbyt/domain/sale/repository/SaleTagRepository.java
  server/src/main/java/com/hobbyt/domain/sale/service/ProductService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleTagService.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/error/exception/ProductNotExistException.java
  server/src/main/java/com/hobbyt/global/error/exception/SaleNotExistException.java
Labels: Backend, 🌟Feature

#110 feat: 판매 게시글 좋아요 구현
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleLikeController.java
  server/src/main/java/com/hobbyt/domain/sale/entity/SaleLike.java
  server/src/main/java/com/hobbyt/domain/sale/repository/SaleLikeRepository.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleLikeService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
Labels: Backend, 🌟Feature

#113 feat: 블로그 게시글 수정삭제 #105
  client/pages/blogwrite.tsx
  client/pages/post/edit/[postId].tsx
  client/src/api/blogApi.tsx
  client/src/components/Modal/EditModal.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogEditComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/ToastUI/TextBlogEditor.tsx
  client/src/components/ToastUI/TitleInput.tsx
  client/src/state/BlogPostState.tsx
  client/src/state/UserState.tsx
Labels: Frontend, 🌟Feature

#111 feat: 판매 게시글 상세조회
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java
  server/src/main/java/com/hobbyt/domain/sale/repository/ProductRepository.java
  server/src/main/java/com/hobbyt/domain/sale/repository/SaleRepository.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/java/com/hobbyt/domain/tag/repository/CustomTagRepository.java
  server/src/main/java/com/hobbyt/domain/tag/repository/CustomTagRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/tag/repository/TagRepository.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
Labels: Backend, 🌟Feature

#115 feat: 개인홈 댓글 리스트 #114
  client/src/api/blogApi.tsx
  client/src/api/tabApi.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
  client/src/components/Tab/Tab.tsx
  client/src/type/blogType.tsx
Labels: Frontend, 🌟Feature

#117 Feat/seongho/priavte likes #116
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomePostLikeResponse.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeRequest.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeServiceDto.java
  server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java
  server/src/main/java/com/hobbyt/domain/search/dto/SearchRequest.java
  server/src/main/java/com/hobbyt/global/entity/OrderBy.java
Labels: Backend, 🚀API

#120 feat: 판매 게시글 복잡한 조회 구현
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeRequest.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeSaleResponse.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/SaleCard.java
  server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java
  server/src/main/java/com/hobbyt/domain/search/controller/SearchController.java
  server/src/main/java/com/hobbyt/domain/search/dto/SaleCard.java
  server/src/main/java/com/hobbyt/domain/search/dto/SearchSaleResponse.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepository.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/search/service/SearchService.java
  server/src/main/java/com/hobbyt/domain/search/service/SearchServiceImpl.java
  server/src/main/java/com/hobbyt/global/entity/OrderBy.java
  server/src/test/java/com/hobbyt/domain/member/controller/AuthControllerTest.java
Labels: 🤬BugFix, Backend, 🌟Feature

#122 refactor: 판매 게시글 상세조회 전달 데이터 추가
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java
  server/src/main/java/com/hobbyt/domain/sale/repository/SaleRepository.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
Labels: 🏭Refactor, Backend

#124 feat: 개인홈 좋아요 리스트 구현 #123
  client/src/api/blogApi.tsx
  client/src/api/tabApi.tsx
  client/src/components/Button/FilterButton.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/ViewLikeWrite/LikeCount.tsx
  client/src/components/ViewLikeWrite/LikeHandle.tsx
  client/src/components/ViewLikeWrite/LikeHover.tsx
  client/src/state/BlogPostState.tsx
  client/src/type/blogType.tsx
Labels: Frontend, 🌟Feature

#128 feat: 개인홈 판매 리스트 #127
  client/dummy/blogdummy.tsx
  client/pages/blog.tsx
  client/pages/blog/follow.tsx
  client/src/api/blogApi.tsx
  client/src/api/profileApi.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Follower.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tab/TabArr.tsx
  client/src/image/pictureDefalut.svg
  client/src/image/saleDImage.svg
  client/src/image/userDImage.svg
Labels: Frontend, 🌟Feature

#130 refactor: 로그인, pw변경 요구사항 변경 반영
  server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java
  server/src/main/java/com/hobbyt/domain/member/dto/LoginDto.java
  server/src/main/java/com/hobbyt/domain/member/dto/response/LoginResponse.java
  server/src/main/java/com/hobbyt/domain/member/service/AuthService.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/test/java/com/hobbyt/domain/member/controller/AuthControllerTest.java
  server/src/test/java/com/hobbyt/domain/member/service/AuthServiceTest.java
Labels: 🏭Refactor, Backend

#131 refactor: 판매 게시글관련 내용 수정
  server/src/main/java/com/hobbyt/domain/privatehome/dto/SaleCard.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Period.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java
  server/src/main/java/com/hobbyt/domain/search/dto/SaleCard.java
Labels: 🏭Refactor, Backend

#132 fix: 주간 인기게시물 조회 (#125)
  server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
Labels: 🤬BugFix, Backend, 🚀API

#136 feat: 팔로우 구현
  server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java
  server/src/main/java/com/hobbyt/domain/member/entity/Follow.java
  server/src/main/java/com/hobbyt/domain/member/repository/FollowRepository.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
Labels: Backend, 🌟Feature

#137 feat: 메인페이지 인기 블로거, 작품 조회 api 구현 (#135)
  server/src/main/java/com/hobbyt/domain/main/controller/MainController.java
  server/src/main/java/com/hobbyt/domain/main/dto/HotBloggerResponse.java
  server/src/main/java/com/hobbyt/domain/main/dto/SaleRequest.java
  server/src/main/java/com/hobbyt/domain/main/dto/SaleResponse.java
  server/src/main/java/com/hobbyt/domain/main/repository/MainRepository.java
  server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/main/service/MainService.java
Labels: Backend, 🚀API

#138 fix: 판매게시글 관련 문제해결
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Delivery.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Period.java
  server/src/main/java/com/hobbyt/domain/sale/service/ProductService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/java/com/hobbyt/global/entity/Account.java
Labels: 🤬BugFix, 🏭Refactor, Backend

#139 fix: is로 시작하는 필드 매핑문제 해결
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/SaleCard.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java
  server/src/main/java/com/hobbyt/domain/search/dto/SaleCard.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
Labels: 🤬BugFix

#140 refactor: 변수명 변경전으로 유지한 상태로 boolean 타입 매핑 문제해결
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
Labels: 🏭Refactor

#142 feat: 메인페이지 인기 블로거 api 최종 구현 (#135)
  server/src/main/java/com/hobbyt/domain/main/dto/HotBloggerResponse.java
  server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java
Labels: Backend, 🚀API

#144 feat: 판매 게시글 CRD + 좋아요 구현, 기타에러 수정
  client/pages/sale/[id].tsx
  client/pages/saledetail.tsx
  client/pages/salewrite.tsx
  client/src/api/errorHandler.tsx
  client/src/api/saleApi.tsx
  client/src/components/Button/SubmitButton.tsx
  client/src/components/Modal/PaymentModal.tsx
  client/src/components/Nav/NavArr.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/SaleDetail/Agreement.tsx
  client/src/components/Page/SaleDetail/InputForPurchase.tsx
  client/src/components/Page/SaleDetail/ProductContent.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Page/SaleDetail/ProductList.tsx
  client/src/components/Page/SaleDetail/ProductTitle.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/AccountInput.tsx
  client/src/components/Page/SaleWrite/PostWriteStyle.tsx
  client/src/components/Page/SaleWrite/ProcessUrlInput.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/SaleWrite/RefundGuideInput.tsx
  client/src/components/Page/SaleWrite/SalePeriodInput.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/Page/SaleWrite/SendTimeInput.tsx
  client/src/components/Page/SaleWrite/ShippingInfoInput.tsx
  client/src/components/Page/SaleWrite/WarningInput.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/Sign/SignupForm.tsx
  client/src/components/Page/UserInfo/AccountInfo.tsx
  client/src/components/Page/UserInfo/PasswordInfo.tsx
  client/src/state/SaleState.tsx
  client/src/state/UserState.tsx
  client/src/type/saleType.tsx
Labels: 🤬BugFix, 🏭Refactor, Frontend, 🌟Feature

#145 feat: NavBar 프로필 이미지
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Page/UserInfo/AccountInfo.tsx
  client/src/state/UserState.tsx
Labels: Frontend, 🌟Feature

#147 feat: 알림 기능 구현중 #146
  client/src/api/noticeApi.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Follower.tsx
  client/src/components/List/NoticeList.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/UserInfo/AccountInfo.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tab/TabArr.tsx
  client/src/state/UserState.tsx
Labels: Frontend, 🌟Feature
