Repository ko9612/Hobbyt, pull requests merged in 2023-05, with the labels that each got.

#282 feat: 내 정보 관리, 메인, 검색 페이지 반응형 #274
  client/pages/_app.tsx
  client/pages/blog/[userId].tsx
  client/pages/index.tsx
  client/pages/message.tsx
  client/pages/mypage/[userId].tsx
  client/pages/search.tsx
  client/src/components/Button/BackButton.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/NoticeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Modal/NoticeModal.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/MyList/MyInfoList.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/Search/SearchBar.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Search/SearchSales.tsx
  client/src/components/Page/UserHome/BlogSaleInfo.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/Page/UserHome/Following.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/Page/UserInfo/InfoStyle.tsx
  client/src/components/Page/UserInfo/PasswordInfo.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tab/TabArr.tsx
  client/styles/globals.css
Labels: 🎨CSS, Frontend, 🌟Feature

#283 style: 구매상세, 결제 모달 반응형 #274
  client/src/components/Button/DMButton.tsx
  client/src/components/Button/DefalutButton.tsx
  client/src/components/Button/SubmitButton.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Modal/PaymentModal.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderInfo.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/OrderListInfo/PurChaserEditInfo.tsx
  client/src/components/Page/OrderListInfo/PurChaserInfo.tsx
  client/src/components/Page/OrderListInfo/SellerInfo.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
Labels: 🎨CSS, Frontend, 🌟Feature

#284 style: 판매 상세 반응형 + 주석, 코드 정리 #274
  client/pages/index.tsx
  client/src/api/blogApi.tsx
  client/src/api/errorHandler.tsx
  client/src/components/Button/FilterButton.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Modal/UnFollowModal.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/OrderListInfo/PurChaserEditInfo.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Page/SaleDetail/ProductList.tsx
  client/src/components/Page/SaleDetail/ProductTitle.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/Page/Sign/SignupForm.tsx
  client/src/components/Page/UserInfo/PasswordInfo.tsx
  client/src/components/Tab/Tab.tsx
  client/src/util/AddressApi.tsx
  client/styles/globals.css
Labels: 🎨CSS, Frontend

#285 fix: 판매 상세 반응형 수정 #274
  client/src/components/Page/SaleDetail/ProductList.tsx
Labels: 🎨CSS, Frontend

#286 style: 판매글 작성 페이지 반응형 작업 중 #274
  client/src/components/Button/DMButton.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/OrderListInfo/SellerInfo.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Search/SearchSales.tsx
Labels: 🎨CSS, Frontend

#287 style: 글씨크기 수정 #274
  client/src/components/Page/UserInfo/InfoStyle.tsx
Labels: 🎨CSS, Frontend

#288 style:내 블로그 반응형 #274
  client/pages/blog/[userId].tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Page/UserHome/BlogSaleInfo.tsx
  client/src/components/Tab/Tab.tsx
Labels: 🎨CSS, Frontend

#290 style: 판매 리스트, 메인 반응형 수정1 #274
  client/package-lock.json
  client/pages/blog/[userId].tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/image/saleDImage.svg
Labels: 🎨CSS, Frontend

#291 style: 블로그 리스트, 메인, 검색 반응형 수정 #274
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogItem.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/Page/Search/SearchBlog.tsx
Labels: 🎨CSS, Frontend

#292 style: 판매글 작성 및 수정 반응형 #274
  client/src/components/Nav/MobileNav.tsx
  client/src/components/Page/SaleWrite/PostWriteStyle.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/Tag/DefalutTag.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
  client/src/components/Togle/DefalutTogle.tsx
  client/src/type/saleType.tsx
  client/styles/globals.css
Labels: 🎨CSS, Frontend

#293 style:메인 반응형 수정 #274
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogItem.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/SaleItem.tsx
Labels: 🎨CSS, Frontend

#294 style: 블로그 반응형 수정 #274
  client/pages/message.tsx
  client/pages/message/[ChatRoomId].tsx
  client/pages/notice.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Comment/CommentInput.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/FollowerList.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Modal/NoticeModal.tsx
  client/src/components/Modal/PaymentModal.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogEditComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/MyList/PurchaseList.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/src/components/Page/OrderListInfo/SellerInfo.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Search/SearchSales.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/UserHome/Following.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tag/DefalutTag.tsx
  client/src/components/Websoket/MessageList.tsx
  client/src/components/Websoket/socketjs.tsx
Labels: 🎨CSS, Frontend

#295 style: 반응형 수정 #274
  client/pages/mypage/[userId].tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogItem.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/SaleWrite/PostWriteStyle.tsx
Labels: 🎨CSS, Frontend

#296 배포(ver.2)
  client/pages/message.tsx
  client/pages/message/[ChatRoomId].tsx
  client/pages/mypage/[userId].tsx
  client/pages/notice.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogItem.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Comment/CommentInput.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/FollowerList.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Modal/NoticeModal.tsx
  client/src/components/Modal/PaymentModal.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogEditComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/MyList/PurchaseList.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/OrderListInfo/SellerInfo.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Page/SaleWrite/PostWriteStyle.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Search/SearchSales.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/UserHome/Following.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tag/DefalutTag.tsx
  client/src/components/Websoket/MessageList.tsx
  client/src/components/Websoket/socketjs.tsx
Labels: ✅Test, 🖥Deploy

#298 fix: 블로그 검색결과 비공개글 보이는 오류 수정
  client/src/components/Page/Search/SearchBlog.tsx
Labels: 🤬BugFix, Frontend

#299 style: 개인홈 레이아웃 수정 #274
  client/pages/blog/[userId].tsx
Labels: 🤬BugFix, 🎨CSS, Frontend

#301 feat: 비밀번호 재설정 페이지 추가 + 로그인, 회원가입 페이지 레이아웃 수정 #300
  client/pages/blog/[userId].tsx
  client/pages/forgotpw.tsx
  client/pages/repassword.tsx
  client/pages/search.tsx
  client/pages/signin.tsx
  client/src/api/signApi.tsx
  client/src/api/userApi.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Sign/ForgotPasswordForm.tsx
  client/src/components/Page/Sign/SignGuide.tsx
  client/src/components/Page/Sign/SignLogo.tsx
  client/src/components/Page/Sign/SocialForm.tsx
  client/src/type/userTypes.tsx
Labels: Frontend, 🌟Feature

#302 비밀번호 재설정 기능 추가(1차)
  client/pages/forgotpw.tsx
  client/pages/repassword.tsx
  client/pages/signin.tsx
  client/src/api/signApi.tsx
  client/src/api/userApi.tsx
  client/src/components/Page/Sign/ForgotPasswordForm.tsx
  client/src/components/Page/Sign/SignGuide.tsx
  client/src/components/Page/Sign/SignLogo.tsx
  client/src/components/Page/Sign/SocialForm.tsx
  client/src/type/userTypes.tsx
Labels: Frontend, 🌟Feature

#303 Feat/hana/forgot password #300
  client/pages/repassword.tsx
  client/src/api/signApi.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Sign/PatchForgotPassword.tsx
  client/src/components/Page/UserInfo/InfoStyle.tsx
  client/src/util/AddressApi.tsx
  client/src/util/LoginRefresh.tsx
Labels: 🤬BugFix, Frontend, 🌟Feature

#304 배포 test
  client/pages/repassword.tsx
  client/src/api/signApi.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Sign/PatchForgotPassword.tsx
  client/src/components/Page/UserInfo/InfoStyle.tsx
  client/src/util/AddressApi.tsx
  client/src/util/LoginRefresh.tsx
Labels: 🏭Refactor, ✅Test, 🖥Deploy
