Repository ko9612/Hobbyt, pull requests merged in 2023-03, with the labels that each got.

#229 refactor: 프론트 엔드 url 반영
  server/src/main/java/com/hobbyt/global/security/handler/Oauth2SuccessHandler.java
Labels: 🏭Refactor, Backend

#230 fiX: 프론트 배포 관련 수정 #223
  client/next.config.js
Labels: Frontend, 🚀API, 🖥Deploy

#231 fix: 프론트 배포 관련 수정(알림) #223
  client/src/components/Websoket/socketjs.tsx
Labels: Frontend, 🖥Deploy

#232 fix: 프론트 배포 관련 수정(알람) #223
  client/src/components/Websoket/socketjs.tsx
Labels: 🤬BugFix, Frontend, 🖥Deploy

#233 fix: 프론트 배포 관련 수정(알림) #223
  client/pages/index.tsx
Labels: 🤬BugFix, Frontend, 🖥Deploy

#234 fix: 프론트 배포 관련 수정(알람) #223
  client/pages/index.tsx
  client/src/components/Websoket/socketjs.tsx
Labels: 🤬BugFix, Frontend

#236 fix: 웹소켓 적용 #146
  client/pages/index.tsx
Labels: Frontend

#240 feat: 소셜로그인 provider 체크
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/error/exception/OAuth2AuthenticationProcessingException.java
  server/src/main/java/com/hobbyt/global/security/handler/Oauth2FailureHandler.java
  server/src/main/java/com/hobbyt/global/security/handler/Oauth2SuccessHandler.java
  server/src/main/java/com/hobbyt/global/security/service/OAuth2DetailsService.java
  server/src/main/resources/application.yml
Labels: Backend, 🌟Feature

#241 fix: 카드 결제 로그 추가
  server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java
  server/src/main/java/com/hobbyt/domain/member/dto/request/ProfileRequest.java
  server/src/main/java/com/hobbyt/domain/member/entity/Member.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/order/service/OrderService.java
  server/src/test/java/com/hobbyt/util/TestUtil.java
Labels: Backend, 🌟Feature

#242 feat: 프로필 변경 규칙 수정
  server/src/main/java/com/hobbyt/domain/member/entity/Member.java
Labels: Backend, 🌟Feature

#243 fix: validation 타입 문제 해결
  server/src/main/java/com/hobbyt/domain/order/dto/request/OrderImportRequest.java
Labels: 🤬BugFix, Backend

#247 Feat/hana/qa fix #246
  client/pages/blog/[userId]/sale/edit/[saleId].tsx
  client/pages/oauth.tsx
  client/src/api/blogApi.tsx
  client/src/api/profileApi.tsx
  client/src/api/saleApi.tsx
  client/src/api/signApi.tsx
  client/src/api/tabApi.tsx
  client/src/api/userApi.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/FollowerList.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogEditComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/Sign/SignupForm.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/Page/UserHome/UserProfileImage.tsx
  client/src/components/Page/UserInfo/AccountInfo.tsx
  client/src/components/ToastUI/TextBlogEditor.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
  client/src/state/ProfileState.tsx
  client/src/util/AddressApi.tsx
  client/src/util/ImageErrorHandler.tsx
Labels: 🤬BugFix, 🏭Refactor, 🎨CSS, Frontend, 🌟Feature

#248 fix: 판매게시글 썸네일 수정 #246
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/SaleDetail/ProductThumbnail.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
Labels: 🤬BugFix, Frontend

#250 fix:블로그,이미지 수정 #246
  client/pages/index.tsx
  client/src/components/Button/DMButton.tsx
  client/src/components/Button/DefalutButton.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/NoticeList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/SaleDetail/ProductTitle.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/UserHome/Following.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/UserProfileImage.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
  client/src/components/ViewLikeWrite/LikeHandle.tsx
  client/src/components/Websoket/ChatRoom.tsx
  client/src/state/BlogPostState.tsx
Labels: 🤬BugFix, Frontend

#251 feat: 1차 QA 내용 반영
  server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/response/OrderDetails.java
  server/src/main/java/com/hobbyt/domain/mypage/repository/MyPageRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostController.java
  server/src/main/java/com/hobbyt/domain/post/service/PostService.java
  server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java
  server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/security/handler/Oauth2FailureHandler.java
  server/src/main/java/com/hobbyt/global/security/service/OAuth2DetailsService.java
  server/src/test/java/com/hobbyt/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MemberServiceTest.java
Labels: Backend, 🌟Feature

#252 fix: 1차 QA에러들 수정 #246
  client/src/api/profileApi.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/image/userProfile_ex.jpeg
Labels: 🤬BugFix, Frontend

#253 fix: 결제 IMP_Code 수정 #246
  client/src/util/Payment.tsx
Labels: 🤬BugFix, Frontend

#254 refactor: 코드 정리
  server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java
  server/src/main/java/com/hobbyt/domain/member/controller/MailController.java
  server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java
  server/src/main/java/com/hobbyt/domain/member/service/AuthService.java
  server/src/main/java/com/hobbyt/domain/member/service/AuthenticationCodeGenerator.java
  server/src/main/java/com/hobbyt/domain/member/service/CodeGenerator.java
  server/src/main/java/com/hobbyt/domain/member/service/DefaultImage.java
  server/src/main/java/com/hobbyt/domain/member/service/Email.java
  server/src/main/java/com/hobbyt/domain/member/service/HtmlTemplate.java
  server/src/main/java/com/hobbyt/domain/member/service/MailContentBuilder.java
  server/src/main/java/com/hobbyt/domain/member/service/MailService.java
  server/src/main/java/com/hobbyt/domain/member/service/MailerSender.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberQueryService.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/notification/service/SseService.java
  server/src/main/java/com/hobbyt/global/redis/RedisService.java
  server/src/test/java/com/hobbyt/domain/member/controller/AuthControllerTest.java
  server/src/test/java/com/hobbyt/domain/member/controller/MemberControllerTest.java
  server/src/test/java/com/hobbyt/domain/member/service/AuthServiceTest.java
  server/src/test/java/com/hobbyt/domain/member/service/AuthenticationCodeTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MailServiceTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MailerSenderTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MemberServiceTest.java
Labels: 🏭Refactor, Backend

#256 fix: 2차QA 수정 #255
  client/pages/blog/[userId].tsx
  client/pages/blog/[userId]/blogwrite.tsx
  client/pages/blog/[userId]/follower.tsx
  client/pages/blog/[userId]/following.tsx
  client/pages/blog/[userId]/post/[id].tsx
  client/pages/blog/[userId]/post/edit/[postId].tsx
  client/pages/blog/[userId]/profile.tsx
  client/pages/blog/[userId]/sale/[id].tsx
  client/pages/blog/[userId]/sale/edit/[saleId].tsx
  client/pages/blog/[userId]/salewrite.tsx
  client/pages/index.tsx
  client/src/api/tabApi.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/FollowerList.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/NoticeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Modal/UnFollowModal.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/Page/UserHome/Following.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/Page/UserHome/UserProfileImage.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/ToastUI/TextViewer.tsx
  client/src/components/Websoket/MessageList.tsx
Labels: Frontend, ❕Issue

#257 fix: 2차 QA 프로필, 댓글 수정 #255
  client/src/api/tabApi.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/Comment/CommentInput.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/FollowerList.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Modal/EditModal.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/Page/UserHome/Following.tsx
Labels: Frontend, ❕Issue

#258 fix: 2차 QA 수정(3) #255
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/Comment/CommentInput.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
Labels: Frontend, ❕Issue

#259 fix: 2차 QA 무한 스크롤 #255
  client/src/api/tabApi.tsx
  client/src/components/Button/MyLikeFilterBut.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/FollowerList.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Page/BlogWrite/BlogEditComponent.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Search/SearchSales.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/Tab/Tab.tsx
  client/src/state/BlogPostState.tsx
  client/src/type/blogType.tsx
  client/src/type/saleType.tsx
Labels: Frontend, ❕Issue

#262 fix: 3차 QA 무한스크롤 수정 #255
  client/src/api/tabApi.tsx
  client/src/components/Button/MyLikeFilterBut.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Tab/Tab.tsx
Labels: Frontend, ❕Issue

#263 fix: 2차 QA 수정_2 #255
  client/pages/oauth.tsx
  client/src/api/blogApi.tsx
  client/src/api/saleApi.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/ViewLikeWrite/LikeHandle.tsx
  client/src/components/ViewLikeWrite/LikeHover.tsx
  client/src/type/saleType.tsx
Labels: 🤬BugFix, Frontend

#265 fix: 3차 QA 썸네일 이미지 수정
  client/src/components/List/BlogItem.tsx
  client/src/components/List/Comment/CommentInput.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/type/blogType.tsx
Labels: Frontend, ❕Issue

#267 fix: 3차 QA 마이페이지 수정 #255
  client/package-lock.json
  client/package.json
  client/src/api/tabApi.tsx
  client/src/components/Category/MyPageCategory.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/MyList/PurchaseList.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
Labels: Frontend, ❕Issue
