Repository ko9612/Hobbyt, pull requests merged in 2023-02, with the labels that each got.

#148 feat: 판매 게시글 U + 주소검색api 컴포넌트 분리
  client/pages/sale/edit/[saleId].tsx
  client/src/components/Modal/PaymentModal.tsx
  client/src/components/Page/SaleDetail/ProductContent.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/UserInfo/AddressApi.tsx
  client/src/components/Page/UserInfo/AddressInfo.tsx
  client/src/components/ToastUI/TitleInput.tsx
Labels: 🏭Refactor, Frontend, 🌟Feature

#149 feat: 알림 작업중#146
  client/package-lock.json
  client/package.json
  client/src/components/List/NoticeList.tsx
  client/src/components/Page/Sign/SigninForm.tsx
Labels: Frontend, 🌟Feature

#151 feat: saleItem 수정 #150
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Page/Search/SearchSales.tsx
Labels: 🏭Refactor, Frontend

#152 feat: sale 수정 #150
  client/src/components/Button/FilterButton.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Tab/Tab.tsx
Labels: 🏭Refactor, Frontend

#153 feat: 알림 테스트 #146
  client/package-lock.json
  client/package.json
  client/src/components/List/NoticeList.tsx
  client/src/components/Page/Sign/SigninForm.tsx
Labels: ✅Test, 🌟Feature

#154 fix: 검색 조건 추가
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeRequest.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeServiceDto.java
  server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
Labels: 🤬BugFix

#156 feat: 검색 페이지 구현-블로그,판매
  client/pages/search.tsx
  client/src/api/tabApi.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/Search/SearchBar.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Search/SearchSales.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
  client/src/components/Tab/Tab.tsx
  client/src/type/blogType.tsx
  client/src/type/saleType.tsx
Labels: 🏭Refactor, Frontend, 🌟Feature

#159 feat: 주문관련 api 구현
  server/build.gradle
  server/src/main/java/com/hobbyt/domain/member/entity/Recipient.java
  server/src/main/java/com/hobbyt/domain/notification/entity/NotificationType.java
  server/src/main/java/com/hobbyt/domain/notification/service/NotificationEventHandler.java
  server/src/main/java/com/hobbyt/domain/order/controller/OrderController.java
  server/src/main/java/com/hobbyt/domain/order/dto/CancelRequest.java
  server/src/main/java/com/hobbyt/domain/order/dto/OrderImportRequest.java
  server/src/main/java/com/hobbyt/domain/order/dto/OrderInfo.java
  server/src/main/java/com/hobbyt/domain/order/dto/ProductDto.java
  server/src/main/java/com/hobbyt/domain/order/entity/Order.java
  server/src/main/java/com/hobbyt/domain/order/entity/OrderItem.java
  server/src/main/java/com/hobbyt/domain/order/entity/OrderStatus.java
  server/src/main/java/com/hobbyt/domain/order/entity/PayMethod.java
  server/src/main/java/com/hobbyt/domain/order/entity/Payments.java
  server/src/main/java/com/hobbyt/domain/order/repository/OrderRepository.java
  server/src/main/java/com/hobbyt/domain/order/service/OrderService.java
  server/src/main/java/com/hobbyt/domain/order/service/PaymentService.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Delivery.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Product.java
  server/src/main/java/com/hobbyt/domain/sale/repository/SaleRepository.java
  server/src/main/java/com/hobbyt/domain/sale/service/ProductService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleLikeService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/java/com/hobbyt/global/error/exception/ImpossibleCancelException.java
  server/src/main/java/com/hobbyt/global/error/exception/NotEnoughStockException.java
  server/src/main/java/com/hobbyt/global/error/exception/OrderNotExistException.java
  server/src/main/java/com/hobbyt/global/error/exception/PaymentException.java
  server/src/main/resources/application.yml
  server/src/test/java/com/hobbyt/domain/member/controller/AuthControllerTest.java
Labels: Backend, 🌟Feature

#162 refactor: 검색, 개인홈 판매글, 금주의 작품 반환값 추가, 이름 변경
  server/src/main/java/com/hobbyt/domain/main/dto/SaleResponse.java
  server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/SaleCard.java
  server/src/main/java/com/hobbyt/domain/search/dto/SaleCard.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
Labels: 🏭Refactor, Backend

#165 feat:팔로잉,팔로우 #164
  client/pages/blog/follower.tsx
  client/pages/blog/following.tsx
  client/src/api/tabApi.tsx
  client/src/components/Button/FollowButton.tsx
  client/src/components/List/Follower.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/Page/UserHome/Following.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tab/TabArr.tsx
Labels: Frontend, 🌟Feature

#166 feat: 메인 페이지 구현 + 검색 페이지 수정 #158
  client/pages/index.tsx
  client/pages/test.tsx
  client/src/api/MainApi.tsx
  client/src/api/SearchApi.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Search/SearchSales.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
  client/src/type/blogType.tsx
  client/src/type/saleType.tsx
  client/src/type/userTypes.tsx
Labels: 🏭Refactor, Frontend, 🌟Feature

#168 feat: 내 정보의 조회관련 기능 구현
  server/src/main/java/com/hobbyt/domain/member/entity/Recipient.java
  server/src/main/java/com/hobbyt/domain/mypage/controller/MyPageController.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/OrderDetails.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/OrderDto.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/OrderedProductInfo.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/PageDto.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/PageResponse.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/UpdateOrderStatusRequest.java
  server/src/main/java/com/hobbyt/domain/mypage/service/MyPageService.java
  server/src/main/java/com/hobbyt/domain/order/entity/Order.java
  server/src/main/java/com/hobbyt/domain/order/entity/OrderItem.java
  server/src/main/java/com/hobbyt/domain/order/repository/CustomOrderRepository.java
  server/src/main/java/com/hobbyt/domain/order/repository/CustomOrderRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/order/repository/OrderRepository.java
  server/src/main/java/com/hobbyt/domain/order/service/OrderService.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Product.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomProductRepository.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomProductRepositoryImpl.java
  server/src/main/java/com/hobbyt/global/entity/Address.java
Labels: Backend, 🌟Feature

#169 feat: 계좌이체 주문 완, 주문상세조회 구현 중 #167
  client/pages/orderdetail/[id].tsx
  client/pages/orderdetail/[userId]/[id].tsx
  client/pages/sale/edit/[saleId].tsx
  client/pages/sale/edit/[userId]/[saleId].tsx
  client/src/api/OrderApi.tsx
  client/src/api/saleApi.tsx
  client/src/api/tabApi.tsx
  client/src/components/Modal/PaymentModal.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Page/SaleDetail/ProductList.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
  client/src/state/OrderState.tsx
  client/src/state/SaleState.tsx
  client/src/type/OrderType.tsx
  client/src/type/saleType.tsx
  client/src/util/OrederNumber.tsx
Labels: 🏭Refactor, Frontend, 🌟Feature

#171 feat: 팔로잉, 팔로워 목록 조회
  server/src/main/java/com/hobbyt/domain/follow/controller/FollowController.java
  server/src/main/java/com/hobbyt/domain/follow/dto/FollowingDto.java
  server/src/main/java/com/hobbyt/domain/follow/dto/SliceDto.java
  server/src/main/java/com/hobbyt/domain/follow/dto/SliceResponse.java
  server/src/main/java/com/hobbyt/domain/follow/entity/Follow.java
  server/src/main/java/com/hobbyt/domain/follow/repository/CustomFollowRepository.java
  server/src/main/java/com/hobbyt/domain/follow/repository/CustomFollowRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/follow/repository/FollowRepository.java
  server/src/main/java/com/hobbyt/domain/follow/service/FollowService.java
  server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/order/repository/CustomOrderRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomProductRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomSaleTagRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/tag/repository/CustomTagRepositoryImpl.java
Labels: Backend, 🌟Feature

#172 refactor: 판매글, 판매글 수정, 주문 내역 상세, 판매 상세 url 변경, 마이페이지 url 변경
  client/pages/blog/[userId]/sale/[id].tsx
  client/pages/blog/[userId]/sale/edit/[saleId].tsx
  client/pages/mypage/[userId].tsx
  client/pages/mypage/[userId]/orderdetail/[id].tsx
  client/pages/orderdetail/[userId]/[id].tsx
  client/pages/sale/[id].tsx
  client/pages/sale/edit/[userId]/[saleId].tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Modal/PaymentModal.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
  client/src/components/ToastUI/TitleInput.tsx
Labels: 🏭Refactor, Frontend

#173 feat: 주문관련 api 구현, 정리
  server/src/main/java/com/hobbyt/domain/member/entity/Recipient.java
  server/src/main/java/com/hobbyt/domain/mypage/controller/MyPageController.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/OrderDetails.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/OrderDto.java
  server/src/main/java/com/hobbyt/domain/mypage/service/MyPageService.java
  server/src/main/java/com/hobbyt/domain/notification/dto/NotificationEvent.java
  server/src/main/java/com/hobbyt/domain/notification/dto/NotificationResponse.java
  server/src/main/java/com/hobbyt/domain/notification/entity/Notification.java
  server/src/main/java/com/hobbyt/domain/notification/repository/CustomNotificationRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/order/controller/OrderController.java
  server/src/main/java/com/hobbyt/domain/order/dto/CancelRequest.java
  server/src/main/java/com/hobbyt/domain/order/dto/UpdateOrderDetailsRequest.java
  server/src/main/java/com/hobbyt/domain/order/entity/Order.java
  server/src/main/java/com/hobbyt/domain/order/entity/OrderStatus.java
  server/src/main/java/com/hobbyt/domain/order/repository/CustomOrderRepository.java
  server/src/main/java/com/hobbyt/domain/order/repository/CustomOrderRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/order/service/OrderService.java
  server/src/main/java/com/hobbyt/domain/post/service/PostCommentService.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomSaleRepository.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomSaleRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/sale/repository/SaleRepository.java
Labels: 🏭Refactor, Backend, 🌟Feature

#174 refactor: 주문 상태 추가, 주문상세조회 반환값 추가
  server/src/main/java/com/hobbyt/domain/mypage/dto/OrderDetails.java
  server/src/main/java/com/hobbyt/domain/order/entity/OrderStatus.java
Labels: 🏭Refactor, Backend

#176 feat: 폴더 정리
  client/pages/blog/[userId].tsx
  client/pages/blog/[userId]/post/[id].tsx
  client/pages/blog/[userId]/post/edit/[postId].tsx
  client/src/components/Nav/NavArr.tsx
  client/src/components/Nav/NavContent.tsx
Labels: 🏭Refactor, ⚙Setting, Frontend

#178 feat: 폴더 세팅2
  client/pages/blog/[userId]/follower.tsx
  client/pages/blog/[userId]/following.tsx
  client/pages/blog/follower.tsx
  client/pages/blog/following.tsx
  client/src/api/tabApi.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/FollowerList.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/UserHome/Following.tsx
  client/src/components/Page/UserHome/UserProfile.tsx
  client/src/components/Tab/Tab.tsx
Labels: 🏭Refactor, Frontend

#179 refactor: 주문 취소 변경된 요구사항 반영
  server/src/main/java/com/hobbyt/domain/order/entity/Order.java
  server/src/main/java/com/hobbyt/domain/order/service/OrderService.java
Labels: 🏭Refactor, Backend

#180 feat: url정리 + 주문 상세 내역 구현 #167
  client/pages/blog/[userId]/sale/edit/[saleId].tsx
  client/pages/mypage/[userId]/orderdetail/[id].tsx
  client/pages/mypage/[userId]/orderdetail/ordermanagement/[id].tsx
  client/src/api/OrderApi.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContentBuyer.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContentSeller.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/OrderListInfo/PurChaserEditInfo.tsx
  client/src/components/Page/OrderListInfo/PurChaserInfo.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/UserInfo/AddressInfo.tsx
  client/src/util/AddressApi.tsx
Labels: 🏭Refactor, Frontend, 🌟Feature

#183 feat: 판매관리 진행사항#181
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/src/state/OrderState.tsx
Labels: Frontend, 🌟Feature

#184 setting: 폴더,url 수정
  client/pages/blog/[userId]/blogwrite.tsx
  client/pages/blog/[userId]/post/edit/[postId].tsx
  client/pages/blog/[userId]/salewrite.tsx
  client/pages/blog/salewrite.tsx
  client/src/components/Category/CategoryArr.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Page/MyList/PurchaseList.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/src/components/Page/UserHome/BlogSaleInfo.tsx
Labels: ⚙Setting, Frontend

#187 refactor: 내정보, 개인홈, 판매게시글 관련 api 변경된 요구사항 반영
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/mypage/controller/MyPageController.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/MyOrderDto.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/OrderDetails.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/OrderDto.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/OrderedProductInfo.java
  server/src/main/java/com/hobbyt/domain/order/repository/CustomOrderRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/SaleCard.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomProductRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/java/com/hobbyt/global/entity/Article.java
Labels: 🏭Refactor, Backend

#188 Feat/hana/order #167
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderInfo.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
  client/src/state/BlogPostState.tsx
Labels: 🏭Refactor, Frontend, 🌟Feature

#189 feat: 주문상세조회(판매자) 상태 전환 기능 추가 + 판매CRU 썸네일 추가 #167
  client/pages/mypage/[userId]/orderdetail/[...id].tsx
  client/pages/mypage/[userId]/orderdetail/[sellerId]/ordermanagement/[id].tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/src/components/Page/OrderListInfo/DepositInfo.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderInfo.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/OrderListInfo/PurChaserEditInfo.tsx
  client/src/components/Page/OrderListInfo/PurChaserInfo.tsx
  client/src/components/Page/OrderListInfo/SellerInfo.tsx
  client/src/components/Page/SaleDetail/ProductThumbnail.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
  client/src/state/BlogPostState.tsx
  client/src/state/OrderState.tsx
  client/src/state/SaleState.tsx
  client/src/type/OrderType.tsx
  client/src/type/saleType.tsx
Labels: ⚙Setting, Frontend, 🌟Feature

#190 refactor: 프로필, 팔로잉, 팔로워 조회에 팔로잉 확인값 추가
  server/src/main/java/com/hobbyt/domain/follow/controller/FollowController.java
  server/src/main/java/com/hobbyt/domain/follow/dto/FollowDto.java
  server/src/main/java/com/hobbyt/domain/follow/repository/CustomFollowRepository.java
  server/src/main/java/com/hobbyt/domain/follow/repository/CustomFollowRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/follow/service/FollowService.java
  server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java
  server/src/main/java/com/hobbyt/domain/member/dto/response/ProfileResponse.java
  server/src/main/java/com/hobbyt/domain/member/entity/Views.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/order/controller/OrderController.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/test/java/com/hobbyt/domain/member/controller/MemberControllerTest.java
Labels: 🏭Refactor, Backend

#194 feat: 좋아요 조회시 판매 게시글로 조회
  server/src/main/java/com/hobbyt/domain/follow/controller/FollowController.java
  server/src/main/java/com/hobbyt/domain/follow/service/FollowService.java
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java
  server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeSaleLikeResponse.java
  server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java
  server/src/main/java/com/hobbyt/global/dto/SliceDto.java
  server/src/main/java/com/hobbyt/global/dto/SliceResponse.java
Labels: Backend, 🌟Feature

#195 fix: 카드 결제시 발생하는 문제 해결
  server/src/main/java/com/hobbyt/domain/order/entity/Order.java
  server/src/main/java/com/hobbyt/domain/order/entity/Payments.java
  server/src/main/java/com/hobbyt/domain/order/service/OrderService.java
  server/src/main/java/com/hobbyt/global/exception/ExceptionCode.java
Labels: 🤬BugFix, Backend

#196 feat: 카드결제 기능 완료 + 구매상세페이지 수정 #167
  client/.gitignore
  client/src/api/OrderApi.tsx
  client/src/components/Modal/PaymentModal.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/OrderListInfo/PurChaserEditInfo.tsx
  client/src/components/Page/OrderListInfo/PurChaserInfo.tsx
  client/src/components/Page/OrderListInfo/SellerInfo.tsx
  client/src/util/Payment.tsx
Labels: 🏭Refactor, Frontend, 🌟Feature

#197 refactor: 카드결제 완료 후, 로더 발생되도록 수정 #167
  client/src/components/Modal/PaymentModal.tsx
  client/src/util/Payment.tsx
Labels: 🏭Refactor, Frontend

#200 feat: 소셜 로그인
  server/build.gradle
  server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java
  server/src/main/java/com/hobbyt/domain/member/entity/Member.java
  server/src/main/java/com/hobbyt/domain/member/entity/Provider.java
  server/src/main/java/com/hobbyt/domain/member/repository/MemberRepository.java
  server/src/main/java/com/hobbyt/domain/member/service/AuthService.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/security/handler/Oauth2SuccessHandler.java
  server/src/main/java/com/hobbyt/global/security/member/MemberDetails.java
  server/src/main/java/com/hobbyt/global/security/oauth2/GoogleUserInfo.java
  server/src/main/java/com/hobbyt/global/security/oauth2/KakaoUserInfo.java
  server/src/main/java/com/hobbyt/global/security/oauth2/NaverUserInfo.java
  server/src/main/java/com/hobbyt/global/security/oauth2/OAuth2UserInfo.java
  server/src/main/java/com/hobbyt/global/security/service/MemberDetailsService.java
  server/src/main/java/com/hobbyt/global/security/service/OAuth2DetailsService.java
  server/src/main/resources/application.yml
Labels: Backend, 🌟Feature

#201 chore: 소셜로그인 redirect uri에 변경된 도메인 적용
  server/src/main/resources/application.yml
Labels: ⚙Setting, Backend

#203 feat: 썸네일 업로드 + 기타 수정
  client/src/api/blogApi.tsx
  client/src/api/profileApi.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/ToastUI/TextBlogEditor.tsx
  client/src/components/ToastUI/TextEditor.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
Labels: Frontend, 🌟Feature

#205 feat: 썸네일 #204
  client/src/api/blogApi.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogEditComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
Labels: 🎨CSS, Frontend, 🌟Feature

#206 feat: 판매 상세+list 썸네일 출력 #204
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/SaleDetail/ProductThumbnail.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
Labels: Frontend, 🌟Feature

#207 refactor: 썸네일 수정 #204
  client/src/api/blogApi.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
Labels: 🏭Refactor, Frontend

#208 refactor: 판매 썸네일 ui 수정 #204
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/SaleDetail/ProductThumbnail.tsx
Labels: 🏭Refactor, 🌟Feature

#210 chore: 구글 oauth2 설정 추가
  server/src/main/resources/application.yml
Labels: ⚙Setting

#211 feat: 예외처리, 요구사항 변경 반영
  server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java
  server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java
  server/src/main/java/com/hobbyt/domain/member/dto/response/LoginInfo.java
  server/src/main/java/com/hobbyt/domain/member/service/AuthService.java
  server/src/main/java/com/hobbyt/domain/member/service/MailService.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/order/entity/Payments.java
  server/src/main/java/com/hobbyt/global/exception/CMailException.java
  server/src/main/java/com/hobbyt/global/exception/ExceptionCode.java
  server/src/main/java/com/hobbyt/global/exception/InputNotFoundException.java
  server/src/main/java/com/hobbyt/global/exception/LoginFailException.java
  server/src/main/java/com/hobbyt/global/exception/MemberAlreadyLoggedInException.java
  server/src/main/java/com/hobbyt/global/exception/PasswordException.java
  server/src/main/java/com/hobbyt/global/exception/TokenNotValidException.java
  server/src/main/java/com/hobbyt/global/exception/WriterExistException.java
  server/src/test/java/com/hobbyt/domain/member/service/AuthServiceTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MailServiceTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MemberServiceTest.java
Labels: 🏭Refactor, Backend, 🌟Feature

#213 feat: 토큰 만료 예외처리 분리
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/security/CustomAuthenticationEntryPoint.java
  server/src/main/java/com/hobbyt/global/security/filter/JwtAuthenticationFilter.java
  server/src/main/resources/templates/error.html
Labels: Backend, 🌟Feature

#214 feat: 프로필, 판매 게시글 이미지 처리
  server/src/main/java/com/hobbyt/domain/file/service/FileService.java
  server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java
  server/src/main/java/com/hobbyt/domain/member/dto/request/ProfileRequest.java
  server/src/main/java/com/hobbyt/domain/member/entity/Member.java
  server/src/main/java/com/hobbyt/domain/member/repository/MemberRepository.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/ProductDto.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Delivery.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Period.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Product.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomSaleRepository.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomSaleRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/sale/repository/SaleRepository.java
  server/src/main/java/com/hobbyt/domain/sale/service/ProductService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/entity/Account.java
  server/src/main/java/com/hobbyt/global/exception/ExceptionCode.java
  server/src/main/java/com/hobbyt/global/security/exception/CustomAuthenticationEntryPoint.java
  server/src/main/java/com/hobbyt/global/security/service/OAuth2DetailsService.java
  server/src/test/java/com/hobbyt/domain/member/service/MemberServiceTest.java
  server/src/test/java/com/hobbyt/util/TestUtil.java
Labels: 🏭Refactor, Backend, 🌟Feature

#215 feat: 알림임시 #146
  client/pages/_app.tsx
  client/pages/index.tsx
  client/src/Pagenation/Pagenation.tsx
  client/src/api/profileApi.tsx
  client/src/api/tabApi.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Page/UserHome/UserProfileImage.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
Labels: Frontend, 🌟Feature

#216 feat: 알림 임시(2) #146
  client/pages/index.tsx
Labels: Frontend, 🌟Feature

#217 feat: 방문자수 처리
  server/src/main/java/com/hobbyt/domain/member/entity/Member.java
  server/src/main/java/com/hobbyt/domain/member/entity/Views.java
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java
  server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/post/controller/PostController.java
  server/src/main/java/com/hobbyt/domain/post/service/PostService.java
  server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java
  server/src/main/java/com/hobbyt/domain/privatehome/entity/Visit.java
  server/src/main/java/com/hobbyt/domain/privatehome/repository/CustomVisitRepository.java
  server/src/main/java/com/hobbyt/domain/privatehome/repository/CustomVisitRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/privatehome/repository/VisitRepository.java
  server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/resources/application.yml
Labels: Backend, 🌟Feature

#218 refactor: 판매 게시글 이미지 처리방법 변경
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/ProductDto.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Delivery.java
  server/src/main/java/com/hobbyt/domain/sale/service/ProductService.java
  server/src/main/java/com/hobbyt/global/entity/Account.java
  server/src/main/java/com/hobbyt/global/exception/ExceptionCode.java
  server/src/main/resources/application.yml
  server/src/main/resources/static/e048f178-9a96-4f59-a6e9-8991abb700d7.jpg
  server/src/main/resources/static/fffe69e4-8152-478d-ad2c-d37bf0cf4424.jpeg
Labels: 🏭Refactor, Backend

#219 refactor: 판매 게시글 상세조회 반환값 이름 변경
  server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java
Labels: 🏭Refactor

#220 feat: oauth 부가 설정 + 리프레시 토큰 로직 변경(미완) #198
  client/pages/oauth.tsx
  client/src/api/MainApi.tsx
  client/src/api/OrderApi.tsx
  client/src/api/SearchApi.tsx
  client/src/api/blogApi.tsx
  client/src/api/noticeApi.tsx
  client/src/api/profileApi.tsx
  client/src/api/saleApi.tsx
  client/src/api/signApi.tsx
  client/src/api/tabApi.tsx
  client/src/api/userApi.tsx
  client/src/components/Nav/NavContent.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/UserInfo/AccountInfo.tsx
  client/src/components/Page/UserInfo/PasswordInfo.tsx
  client/src/state/UserState.tsx
  client/src/util/LoginRefresh.tsx
  client/src/util/token.tsx
Labels: 🏭Refactor, Frontend, 🌟Feature

#221 feat: 판매글 썸네일 수정 + 판매 제품 이미지 출력 #204
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/SaleDetail/ProductList.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
  client/src/state/SaleState.tsx
  client/src/type/OrderType.tsx
  client/src/type/saleType.tsx
Labels: Frontend, 🌟Feature

#224 fix: build를 위한 코드 수정 #223
  client/next.config.js
  client/package.json
  client/pages/index.tsx
  client/src/Pagenation/Pagenation.tsx
  client/src/api/signApi.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Scroll/InfiniteScroll.tsx
Labels: 🤬BugFix, Frontend, 🖥Deploy

#226 refactor: 토큰 재발급 access token 관련 로직 변경
  server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java
  server/src/main/java/com/hobbyt/domain/member/service/AuthService.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/security/jwt/JwtTokenProvider.java
  server/src/main/java/com/hobbyt/global/security/service/OAuth2DetailsService.java
  server/src/main/resources/application.yml
Labels: 🏭Refactor, Backend

#227 refactor: validation 예외 처리, 코드 정리
  server/src/main/java/com/hobbyt/domain/file/service/FileService.java
  server/src/main/java/com/hobbyt/domain/member/service/AuthService.java
  server/src/main/java/com/hobbyt/domain/member/service/MailService.java
  server/src/main/java/com/hobbyt/domain/member/service/MemberService.java
  server/src/main/java/com/hobbyt/domain/mypage/controller/MyPageController.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/request/UpdateOrderDetailsRequest.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/request/UpdateOrderStatusRequest.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/response/OrderDetails.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/response/PageResponse.java
  server/src/main/java/com/hobbyt/domain/mypage/repository/MyPageRepository.java
  server/src/main/java/com/hobbyt/domain/mypage/repository/MyPageRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/mypage/service/MyPageService.java
  server/src/main/java/com/hobbyt/domain/notification/service/SseService.java
  server/src/main/java/com/hobbyt/domain/order/controller/OrderController.java
  server/src/main/java/com/hobbyt/domain/order/dto/ProductDto.java
  server/src/main/java/com/hobbyt/domain/order/dto/request/OrderImportRequest.java
  server/src/main/java/com/hobbyt/domain/order/dto/request/OrderInfo.java
  server/src/main/java/com/hobbyt/domain/order/dto/request/ProductDto.java
  server/src/main/java/com/hobbyt/domain/order/entity/Order.java
  server/src/main/java/com/hobbyt/domain/order/entity/Payments.java
  server/src/main/java/com/hobbyt/domain/order/repository/OrderRepository.java
  server/src/main/java/com/hobbyt/domain/order/service/OrderService.java
  server/src/main/java/com/hobbyt/domain/post/service/PostCommentService.java
  server/src/main/java/com/hobbyt/domain/post/service/PostService.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/ProductDto.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Product.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomProductRepository.java
  server/src/main/java/com/hobbyt/domain/sale/repository/CustomProductRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/sale/service/ProductService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/java/com/hobbyt/domain/search/controller/SearchController.java
  server/src/main/java/com/hobbyt/domain/search/dto/request/SearchRequest.java
  server/src/main/java/com/hobbyt/domain/search/dto/response/SearchPostResponse.java
  server/src/main/java/com/hobbyt/domain/search/dto/response/SearchSaleResponse.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepository.java
  server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/search/service/SearchService.java
  server/src/main/java/com/hobbyt/domain/search/service/SearchServiceImpl.java
  server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
  server/src/main/java/com/hobbyt/global/error/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/hobbyt/global/error/dto/FailValidationDto.java
  server/src/main/java/com/hobbyt/global/error/exception/BusinessLogicException.java
  server/src/main/java/com/hobbyt/global/error/exception/ExceptionCode.java
  server/src/main/java/com/hobbyt/global/error/exception/PaymentException.java
  server/src/main/java/com/hobbyt/global/error/exception/SseConnectException.java
  server/src/main/java/com/hobbyt/global/exception/GlobalExceptionAdvice.java
  server/src/main/java/com/hobbyt/global/security/service/MemberDetailsService.java
  server/src/main/java/com/hobbyt/global/security/service/OAuth2DetailsService.java
  server/src/main/resources/application.yml
  server/src/test/java/com/hobbyt/domain/member/service/AuthServiceTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MailServiceTest.java
  server/src/test/java/com/hobbyt/domain/member/service/MemberServiceTest.java
Labels: 🏭Refactor, Backend, 🌟Feature

#228 fix: refresh token 로직 수정 + 테스트 완 #198
  client/src/api/signApi.tsx
  client/src/util/LoginRefresh.tsx
  client/src/util/token.tsx
Labels: 🤬BugFix, Frontend
