Repository ko9612/Hobbyt, pull requests merged in 2023-04, with the labels that each got.

#268 fix: 3차 QA 수정 #255
  client/package-lock.json
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/MyList/PurchaseList.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/src/components/Page/SaleDetail/ProductContent.tsx
  client/src/components/Pagination/Pagination.tsx
Labels: Frontend, ❕Issue

#269 Feat/hana/qa fix #255
  client/package-lock.json
  client/pages/blog/[userId]/blogwrite.tsx
  client/pages/blog/[userId]/post/edit/[postId].tsx
  client/pages/blog/[userId]/profile.tsx
  client/pages/blog/[userId]/sale/edit/[saleId].tsx
  client/pages/blog/[userId]/salewrite.tsx
  client/pages/message.tsx
  client/pages/message/[ChatRoomId].tsx
  client/pages/mypage/[userId].tsx
  client/pages/mypage/[userId]/orderdetail/[...id].tsx
  client/pages/mypage/[userId]/orderdetail/[sellerId]/ordermanagement/[id].tsx
  client/pages/notice.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Page/BlogWrite/BlogEditComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/SaleDetail/ProductList.tsx
  client/src/components/Page/SaleDetail/ProductThumbnail.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/components/Page/SaleWrite/ProductInfoInput.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Search/SearchSales.tsx
  client/src/util/LoginRefresh.tsx
  client/src/util/UrlAccessControl.tsx
Labels: 🤬BugFix, Frontend, 🌟Feature

#270 fix: 4차 QA 수정 #255
  client/.eslintrc.js
  client/pages/blog/[userId].tsx
  client/src/api/blogApi.tsx
  client/src/api/profileApi.tsx
  client/src/components/Button/DMButton.tsx
  client/src/components/Button/InfoEditButton.tsx
  client/src/components/Button/ModalButton.tsx
  client/src/components/Button/ProfileButton.tsx
  client/src/components/Category/MyPageCategory.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Comment/CommentInput.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Modal/DelModal.tsx
  client/src/components/Modal/DeleteModal.tsx
  client/src/components/Modal/EditModal.tsx
  client/src/components/Modal/MsgModal.tsx
  client/src/components/Modal/UnFollowModal.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/SaleDetail/ProductThumbnail.tsx
  client/src/components/Page/Search/SearchSales.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/components/Page/UserHome/Following.tsx
  client/src/components/Page/UserHome/Header.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Pagination/Pagination.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/ToastUI/ThumbnailInput.tsx
  client/src/components/Websoket/ChatRoom.tsx
  client/src/components/Websoket/MessageList.tsx
  client/src/type/blogType.tsx
  client/src/type/saleType.tsx
Labels: Frontend, ❕Issue

#271 test: 파일명 변경 #255
  client/src/api/mainApi.tsx
  client/src/api/orderApi.tsx
  client/src/api/searchApi.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/Modal/PaymentModal.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/OrderListInfo/PurChaserEditInfo.tsx
  client/src/components/Page/Search/SearchBlog.tsx
  client/src/components/Page/Search/SearchSales.tsx
  client/src/util/Payment.tsx
Labels: ✅Test, Frontend, 🚀API

#272 refactor: 코드 리팩토링, 요구사항 변경 반영
  server/src/main/java/com/hobbyt/domain/member/repository/MemberRepository.java
  server/src/main/java/com/hobbyt/domain/mypage/controller/MyPageController.java
  server/src/main/java/com/hobbyt/domain/mypage/dto/response/OrderDetails.java
  server/src/main/java/com/hobbyt/domain/mypage/repository/MyPageRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/mypage/service/MyPageQueryService.java
  server/src/main/java/com/hobbyt/domain/mypage/service/MyPageService.java
  server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java
  server/src/main/java/com/hobbyt/domain/privatehome/repository/PrivateHomeRepository.java
  server/src/main/java/com/hobbyt/domain/privatehome/repository/PrivateHomeRepositoryImpl.java
  server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java
  server/src/main/java/com/hobbyt/domain/privatehome/service/VisitService.java
  server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java
  server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Product.java
  server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java
  server/src/main/java/com/hobbyt/domain/sale/repository/SaleRepository.java
  server/src/main/java/com/hobbyt/domain/sale/service/ProductService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
  server/src/main/java/com/hobbyt/domain/sale/service/SaleTagService.java
  server/src/main/java/com/hobbyt/domain/sale/service/WriteSaleService.java
  server/src/main/java/com/hobbyt/global/security/handler/Oauth2FailureHandler.java
  server/src/main/java/com/hobbyt/global/security/handler/Oauth2SuccessHandler.java
Labels: 🤬BugFix, 🏭Refactor, Backend, 🌟Feature

#273 fix: 4차 QA 수정 #255
  client/package-lock.json
  client/pages/signin.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/NoticeList.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogEditComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/OrderListInfo/OrderDetailContent.tsx
  client/src/components/Page/SaleDetail/ProductThumbnail.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
  client/src/components/Page/SaleWrite/SaleWriteContent.tsx
  client/src/components/Page/Sign/SigninForm.tsx
  client/src/components/Page/UserHome/BlogSaleInfo.tsx
  client/src/components/ToastUI/TextBlogEditor.tsx
  client/src/type/OrderType.tsx
  client/src/util/AddressApi.tsx
  client/styles/globals.css
Labels: 🤬BugFix, Frontend

#275 fix: 5차 QA 수정 #255
  client/src/api/noticeApi.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/Comment/CommentList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/LikeList.tsx
  client/src/components/List/NoticeList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/List/SaleList.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/MyList/PurchaseList.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/src/components/Page/Search/SearchSales.tsx
Labels: Frontend, ❕Issue

#276 fix: 5차 QA수정 #255
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/Page/OrderListInfo/OrderProgress.tsx
  client/src/components/Page/SaleDetail/ProductThumbnail.tsx
  client/src/components/Page/SaleWrite/SaleEditContent.tsx
Labels: 🤬BugFix, Frontend

#277 fix: 5차 QA 수정 #255
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/Page/SaleDetail/ProductContent.tsx
  client/src/components/Page/SaleDetail/ProductGuide.tsx
  client/src/components/Page/SaleDetail/ProductList.tsx
  client/src/components/Page/SaleDetail/ProductThumbnail.tsx
  client/src/components/Page/SaleDetail/SaleDetailContent.tsx
  client/src/util/LoginRefresh.tsx
Labels: 🤬BugFix, Frontend

#279 fix: refresh token 수정 + 반응형 작업 중 #274
  client/pages/index.tsx
  client/src/api/signApi.tsx
  client/src/components/List/BestList/BestBlog.tsx
  client/src/components/List/BestList/BestBlogger.tsx
  client/src/components/List/BestList/BestProduct.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/UserHome/DefaultProfileImg.tsx
  client/src/util/AddressApi.tsx
  client/src/util/LoginRefresh.tsx
Labels: 🤬BugFix, 🎨CSS, Frontend

#280 style: 알림 페이지 반응형 #274
  client/pages/_app.tsx
  client/pages/notice.tsx
  client/src/components/List/NoticeList.tsx
Labels: 🎨CSS, Frontend
