Repository ko9612/Hobbyt, pull requests merged in 2023-06, with the labels that each got.

#306 style: 블로그 반응형#274
  client/pages/_app.tsx
  client/pages/blog/[userId].tsx
  client/src/api/blogApi.tsx
  client/src/api/chatApi.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/Search/SearchBar.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
Labels: 🎨CSS, Frontend

#307 style: border 수정 #274
  client/pages/_app.tsx
Labels: 🎨CSS

#308 Dev -> main pr
  client/pages/_app.tsx
  client/pages/blog/[userId].tsx
  client/src/api/blogApi.tsx
  client/src/api/chatApi.tsx
  client/src/components/List/BlogItem.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/List/Comment/MyCommentList.tsx
  client/src/components/List/SaleItem.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/Search/SearchBar.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/SelectBox/ThreeDotsBox.tsx
Labels: 🖥Deploy

#311 fix: 블로그 검색 리스트 요청 단위 수정 + 블로그 item 레이아웃 수정 #274
  client/src/components/List/BlogItem.tsx
  client/src/components/Page/Search/SearchBlog.tsx
Labels: 🤬BugFix, Frontend

#312 Dev->main pr
  client/src/components/List/BlogItem.tsx
  client/src/components/Page/Search/SearchBlog.tsx
Labels: 🖥Deploy

#313 style:블로그 게시글,상세,프로필 수정, 팔로워 페이지 반응형 #274
  client/pages/blog/[userId]/blogwrite.tsx
  client/pages/blog/[userId]/post/[id].tsx
  client/src/components/Button/FollowButton.tsx
  client/src/components/List/Comment/CommentInput.tsx
  client/src/components/List/FollowerList.tsx
  client/src/components/List/FollowingList.tsx
  client/src/components/Page/BlogWrite/BWComponent.tsx
  client/src/components/Page/BlogWrite/BlogPostDetail.tsx
  client/src/components/Page/UserHome/ProfileEdit.tsx
  client/src/components/Tag/DefalutTag.tsx
  client/styles/globals.css
Labels: 🎨CSS, Frontend

#314 style: 내정보 판매,구매작품,판매관리 반응형 #274
  client/src/components/Category/MyPageCategory.tsx
  client/src/components/Category/ProgressCategory.tsx
  client/src/components/Page/MyList/ProductsList.tsx
  client/src/components/Page/MyList/PurchaseList.tsx
  client/src/components/Page/MyList/SalesManagementList.tsx
  client/styles/globals.css
Labels: 🎨CSS, Frontend

#318 style: 푸터 레이아웃 오류 해결 #274
  client/pages/blog/[userId].tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/List/BlogList.tsx
  client/src/components/Tab/Tab.tsx
Labels: 🎨CSS, 🌟Feature

#320 style: 푸터 레이아웃 수정 #274
  client/src/components/List/BlogList.tsx
Labels: 🎨CSS, Frontend

#321 merge: 푸터 레이아웃 오류 해결
  client/pages/blog/[userId].tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Tab/Tab.tsx
Labels: 🎨CSS, Frontend
